const terms = {
"all" : [
  "I", "a", "no", "go", "so",
  "we", "be", "he", "she", "see",
  "at", "as", "has", "an", "can",
  "and", "had", "by", "my", "the",
  "is", "his", "in", "it", "its",
  "if", "did", "him", "will", "with",
  "on", "not", "long", "get", "when",
  "been", "then", "them", "their", "there",
  "up", "but", "number", "do", "to",
  "into", "you", "two", "one", "have",
  "than", "that", "this", "they", "other",
  "or", "for", "our", "more", "was",
  "day", "way", "man", "what", "which",
  "who", "come", "some", "of", "said",
  "make", "made", "like", "time", "use",
  "write", "these", "people", "each", "find",
  "all", "call", "now", "how", "down",
  "out", "about", "could", "would", "look",
  "water", "her", "were", "are", "part",
  "oil", "from", "first", "many", "word",
  "map", "man", "hand", "land", "plan",
  "plant", "stand", "back", "black", "happened",
  "ask", "add", "after", "animal", "along",
  "across", "fast", "last", "passed", "travel",
  "big", "still", "miss", "list", "little",
  "wind", "river", "listen", "give", "live",
  "end", "well", "tell", "spell", "let",
  "set", "red", "men", "help", "second",
  "next", "best", "left", "step", "very",
  "went", "letter", "better", "together", "never",
  "off", "got", "dog", "song", "top",
  "stop", "rock", "problem", "products", "want",
  "us", "under", "until", "run", "sun",
  "cut", "just", "must", "upon", "hundred",
  "both", "another", "mother", "father", "without",
  "something", "through", "thought", "boy", "world",
  "name", "same", "came", "state", "face",
  "space", "place", "page", "table", "take",
  "line", "give", "life", "side", "mile",
  "fire", "those", "home", "close", "waves"
],
"practice" : [
 "with",
 "when",
"their", "there",
  "than",
  "what", "which",
  "who",
"would",
  "man",
  "stand", "back", "black", "happened",
  "along",
  "across",
  "listen",
  "well", "tell", "let",
  "men", "help", "second",
  "next", "best", "left", "step", "very",
  "went", "letter", "better", "together", "never",
  "off", "got",
  "stop", "want",
  "under", "until",
  "upon", "hundred",
  "both", "another", "mother", "father", "without",
  "something", "through", "thought", "world",
  "state", "face",
  "take",
  "those", "home",
],
"four" : [
  "I",
  "too",
  "food",
  "soon",
  "room",
  "few",
  "new",
  "knew",
  "true",
  "group",
  "America",
  "it's",
  "don't",
  "didn't",
  "I'll",
  "slowly",
  "early",
  "family",
  "only",
  "really",
  "usually",
  "any",
  "city",
  "every",
  "body",
  "money",
  "study",
  "carry",
  "air",
  "girl",
  "birds",
  "school",
  "work",
  "head",
  "think",
  "sentence",
  "question",
  "example",
  "even",
  "complete",
  "friends",
  "over",
  "ever",
  "turn",
  "picture",
  "sure",
  "measure",
  "figure",
  "heard",
  "earth",
  "learn",
  "car",
  "far",
  "farm",
  "hard",
  "large",
  "start",
  "mark",
  "notice",
  "since",
  "piece",
  "our",
  "house",
  "south",
  "hours",
  "ground",
  "found",
  "sound",
  "around",
  "mountain",
  "Indian",
  "vowel",
  "town",
  "however",
  "sometimes",
  "himself",
  "country",
  "does",
  "great",
  "today",
  "once",
  "saw",
  "draw",
  "unit",
  "music",
  "here",
  "four",
  "often",
  "move",
  "kind",
  "area",
  "different",
  "certain",
  "covered",
  "several",
  "pattern",
  "numeral",
  "paper",
  "later",
  "answer",
  "remember",
],
}


const praise = [
  "Good job!",
  "Amazing!",
  "Well done!",
  "Great work!",
  "Bravo!",
  "Wow!",
  "Fantastic!",
  "Outstanding!",
  "Incredible!",
  "Way to go!",
  "Nice job!",
];
